app = "oanda-rsi-bot"

primary_region = "fra"

[build]
  image = "python:3.10"

[processes]
  app = "python oanda_rsi_bot.py"

[experimental]
  auto_start = true
  auto_stop = false
  restart = "always"
