app = "oanda-rsi-bot"
primary_region = "fra"

[build]
  image = "python:3.10"

[env]
  PORT = "8080"

[processes]
  app = "python oanda_rsi_bot.py"

[mounts]
  source = "bot_data"
  destination = "/data"

[experimental]
  auto_start = true
  auto_stop = false
  restart = "always"
